site_name: mypygui

theme:
    name: readthedocs

nav:
  - Home : 'index.md'
  - User Guide :
      - Getting Started : 'user-guide/getting-started.md'
  - Objects :
      - Browser Window : 'objects/browser-window.md'
      - Page : 'objects/page.md'
  - Page :
      - scripts : 'page/scripts.md'
      - css : 'page/css.md'
      - html : 'page/html.md'
      - Object Models :
          - CSSOM : 'page/object-models/cssom.md'
          - DOM : 'page/object-models/dom.md'
          - Render Tree : 'page/object-models/render-tree.md'
  - Utilities :
      - Asynchronous : 'utilities/asynchronous.md'
      - File System : 'utilities/fs.md'
      - Logging : 'utilities/logging.md'
  - Services :
      - Resource Handling : 'services/resource_handling.md'
      - Events : 'services/events.md'
      - Rendering : 'services/rendering.md'
      - Worker : 'services/worker.md'
      - Layout Managing : 'services/layout_managing.md'
      - Service Provider : 'services/service_provider.md' 
